// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Core.Data;

#nullable disable

namespace QuizApp.Core.Data.Migrations
{
    [DbContext(typeof(QuizAppDBContext))]
    [Migration("20230607034418_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Core.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TimeTaken")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.ParticipantResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuestionGroupId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TimeTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("QuestionGroupId")
                        .IsUnique();

                    b.HasIndex("QuestionGroupId1");

                    b.ToTable("ParticipantResult");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option5")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Option6")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.QuestionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("QuestionGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37b8b1e7-12de-4303-a91d-89b3543ad139"),
                            Name = "Graphic Design",
                            TopicId = new Guid("92941242-7e5b-4323-af1a-54f03e2a3c63")
                        });
                });

            modelBuilder.Entity("QuizApp.Core.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92941242-7e5b-4323-af1a-54f03e2a3c63"),
                            Name = "Popular"
                        });
                });

            modelBuilder.Entity("QuizApp.Core.Entities.ParticipantResult", b =>
                {
                    b.HasOne("QuizApp.Core.Entities.Participant", "Participant")
                        .WithMany("ParticipantResults")
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("FK_ParticipantResults_Participant");

                    b.HasOne("QuizApp.Core.Entities.QuestionGroup", null)
                        .WithOne("ParticipantResult")
                        .HasForeignKey("QuizApp.Core.Entities.ParticipantResult", "QuestionGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_ParticipantResults_QuestionGroup");

                    b.HasOne("QuizApp.Core.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany()
                        .HasForeignKey("QuestionGroupId1");

                    b.Navigation("Participant");

                    b.Navigation("QuestionGroup");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.Question", b =>
                {
                    b.HasOne("QuizApp.Core.Entities.QuestionGroup", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionGroup_Questions");

                    b.Navigation("QuestionGroup");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.QuestionGroup", b =>
                {
                    b.HasOne("QuizApp.Core.Entities.Topic", "Topic")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionGroups_Topic");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.Participant", b =>
                {
                    b.Navigation("ParticipantResults");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.QuestionGroup", b =>
                {
                    b.Navigation("ParticipantResult");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizApp.Core.Entities.Topic", b =>
                {
                    b.Navigation("QuestionGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
